image: python:3.10

stages:
  - test

before_script:
  - python -V
  - python -m venv venv
  - source venv/bin/activate
  - pip install -U pip
  - pip install .

test:
  stage: test
  script: python -m unittest test.py
